# Generated by Django 5.0.3 on 2024-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
