# Generated by Django 5.0.3 on 2024-05-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postplatform', '0004_alter_posts_date_alter_posts_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
