# Generated by Django 5.0.3 on 2024-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postplatform', '0012_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
