# Generated by Django 5.0.3 on 2024-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postplatform', '0014_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(default='', upload_to='user_posts_file'),
        ),
    ]
