# Generated by Django 5.0.3 on 2024-06-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postplatform', '0016_posts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
