# Generated by Django 5.0.3 on 2024-06-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postplatform', '0019_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
